//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Scripts/Player/PlayerController/MainControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainControls"",
    ""maps"": [
        {
            ""name"": ""PlayerControls"",
            ""id"": ""1db2a64a-d9cc-4ff5-aa50-7b50379ea22a"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""651c0b71-06c9-42eb-b718-d5702bbd97e8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cybernetic"",
                    ""type"": ""Button"",
                    ""id"": ""0bb6ef1d-a236-477f-b42d-902fa7751637"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Button"",
                    ""id"": ""dffd6d54-91c7-455a-9b72-15a12ef19bba"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon1"",
                    ""type"": ""Button"",
                    ""id"": ""fbb66b48-7326-4ad6-befa-a0e4a7aced70"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon2"",
                    ""type"": ""Button"",
                    ""id"": ""ba82b479-3dc8-4776-ba8a-049be02c7b5b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon3"",
                    ""type"": ""Button"",
                    ""id"": ""122a5c58-c5bb-4cef-89fb-55c21edeb20e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon3Up"",
                    ""type"": ""Button"",
                    ""id"": ""95382426-c98c-4153-b10d-eb5725c7c357"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon4"",
                    ""type"": ""Button"",
                    ""id"": ""4e96a7e4-f78d-414a-92bd-1ead0ddfdc43"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon4Up"",
                    ""type"": ""Button"",
                    ""id"": ""62835ad7-3bb9-45e2-beea-361e0d200959"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Utility5"",
                    ""type"": ""Button"",
                    ""id"": ""4bdd5e60-acee-4fac-a420-f697ab66dd7d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Utility6"",
                    ""type"": ""Button"",
                    ""id"": ""b530ee02-3bd9-4155-bb41-a0f4e6c1cd38"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Utility7"",
                    ""type"": ""Button"",
                    ""id"": ""49e88c44-17c8-471b-9918-4491cfd8950c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Utility8"",
                    ""type"": ""Button"",
                    ""id"": ""847b6756-9293-4a4a-a026-86c41982f570"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Utility9"",
                    ""type"": ""Button"",
                    ""id"": ""5d19ddbc-c6d0-493c-844b-3746d3df565a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Utility10"",
                    ""type"": ""Button"",
                    ""id"": ""5ae7115c-094b-4711-a78a-64861ae3a56d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Utility11"",
                    ""type"": ""Button"",
                    ""id"": ""2085f2dd-1de1-4e5a-8b34-092d3c66558e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Utility12"",
                    ""type"": ""Button"",
                    ""id"": ""084c74e6-ea34-4b58-9643-907111429551"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""5efb9423-b4b9-4b79-a53a-12dc4ccf1594"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CharacterSheet"",
                    ""type"": ""Button"",
                    ""id"": ""b446bb1c-f975-4b0d-9787-0f784a1b24e6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Options"",
                    ""type"": ""Button"",
                    ""id"": ""15a8f3db-7126-40ef-9fb7-cfc0e26c5841"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""ea7ae4ec-5ec3-496d-9bbd-5cdcb28e1668"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""ec8522fe-4ecd-4c49-883b-a6f44c2ccbcf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bionetic"",
                    ""type"": ""Button"",
                    ""id"": ""a1d20bf2-1b3f-4b23-abc4-304c986b41b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""85765460-ab74-4ab0-8311-535f261f8418"",
                    ""path"": ""2DVector"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2f7e32e9-6ff0-4c3f-940a-b29d085309c3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9e74603f-249f-4438-b7e7-b941161325ff"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ba4cb463-e518-4381-95ed-6dc87563af7f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f2a0b58b-efda-42a8-b765-d1c68bb398f5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""e53144ae-12c3-465a-9087-9c9ad0b5de79"",
                    ""path"": ""2DVector"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7be07e4a-dcf8-4a77-8df8-992e3142f7cd"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""39ee5b89-6645-416c-bc58-c2db838556aa"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bfc58305-9104-4c99-a769-9a87c18ea68d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""05f37cee-edd8-46eb-96ee-738e76581028"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f36494f6-304b-46de-94bf-505b98e7c47d"",
                    ""path"": ""<DualShockGamepad>/leftStick"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4a5a3e8-9836-4f36-8fa2-bcd1f9ea9358"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ca1ac81-f0ba-4e15-92a5-40bf2e308e71"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12353720-a083-4e25-b1ce-6e5496268b0c"",
                    ""path"": ""<DualShockGamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a705359-c572-4e22-8889-cf799ce2711c"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d461b773-9f31-42e0-8a3d-608fe0aeec09"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3456814-e5ca-4c34-8671-9f27fea164a8"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfaa0d6c-d6bd-4a75-afa8-424d9a766ca5"",
                    ""path"": ""<DualShockGamepad>/rightTrigger"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8483015-7e6b-4dfd-a818-269fed05f8cb"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b71927e-e2b7-44b8-8521-a6d97f073eec"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f946cab-37a5-42dd-9272-105fc7af7789"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""528359af-4839-453b-b301-bfa582e4f07b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8050d093-026c-448d-b946-e0bf930c67a9"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9aeae442-6871-471e-a9c8-9639eff932d2"",
                    ""path"": ""<DualShockGamepad>/leftTrigger"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1d492f9-19db-497f-bea4-3e53760102c6"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6cfae3f6-20dd-4598-a901-13bea45d805d"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e656370-5a34-41c5-93f0-10e969c949f4"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54952573-f319-41c0-b17d-bda48252ccfc"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Utility5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8aca305-fb51-4205-a925-fffbf3427ec2"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Utility6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03ba0bf6-8299-4b67-9a19-e7b1ce0f994c"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Utility7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9215f5f5-b616-42c6-946a-dc0e7163dad4"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Utility8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6fb17fd-7553-471d-8411-e26f6ffe494b"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Utility9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea36ce84-45fd-453d-b3e8-26072d29ce21"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Utility10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9eb5824-da2f-4c21-8179-167b5f766a7e"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2e226bd-9d8a-47c1-ad63-3cf10391df4d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterSheet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d17bd076-f1b9-4128-a7ac-b30f72d1f650"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Options"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5ca5c3d-b319-4f7e-9162-ac30c3f3b71b"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b416720-9d8d-4700-971a-cc08ee303bfd"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5828920e-1900-4af0-a3b9-029da044492a"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Utility11"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf65dbdf-5a9f-4649-95eb-bc16e7d0b0d8"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Utility12"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2f8f67d-cf8c-435d-904e-b0f225525dfa"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cybernetic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb477c40-1291-4c10-ac61-7fd057435371"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon4Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5a77553-68db-49bc-820c-f7a2046ae2a6"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon4Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a06f3457-b27e-4bae-8632-cc1f0d1a9b30"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon4Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e44b4418-5d7d-47c2-9481-1b19fa55db69"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon3Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1971ed0-01a9-438c-98bd-47d6776131ec"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon3Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5d46f02-e191-4f7e-8adf-ebc62c94cab4"",
                    ""path"": ""<DualShockGamepad>/leftTrigger"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon3Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbc1ded8-2558-4fbd-bba1-0beaf6ec7a20"",
                    ""path"": ""<Keyboard>/#(Q)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bionetic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerControls
        m_PlayerControls = asset.FindActionMap("PlayerControls", throwIfNotFound: true);
        m_PlayerControls_Movement = m_PlayerControls.FindAction("Movement", throwIfNotFound: true);
        m_PlayerControls_Cybernetic = m_PlayerControls.FindAction("Cybernetic", throwIfNotFound: true);
        m_PlayerControls_Look = m_PlayerControls.FindAction("Look", throwIfNotFound: true);
        m_PlayerControls_Weapon1 = m_PlayerControls.FindAction("Weapon1", throwIfNotFound: true);
        m_PlayerControls_Weapon2 = m_PlayerControls.FindAction("Weapon2", throwIfNotFound: true);
        m_PlayerControls_Weapon3 = m_PlayerControls.FindAction("Weapon3", throwIfNotFound: true);
        m_PlayerControls_Weapon3Up = m_PlayerControls.FindAction("Weapon3Up", throwIfNotFound: true);
        m_PlayerControls_Weapon4 = m_PlayerControls.FindAction("Weapon4", throwIfNotFound: true);
        m_PlayerControls_Weapon4Up = m_PlayerControls.FindAction("Weapon4Up", throwIfNotFound: true);
        m_PlayerControls_Utility5 = m_PlayerControls.FindAction("Utility5", throwIfNotFound: true);
        m_PlayerControls_Utility6 = m_PlayerControls.FindAction("Utility6", throwIfNotFound: true);
        m_PlayerControls_Utility7 = m_PlayerControls.FindAction("Utility7", throwIfNotFound: true);
        m_PlayerControls_Utility8 = m_PlayerControls.FindAction("Utility8", throwIfNotFound: true);
        m_PlayerControls_Utility9 = m_PlayerControls.FindAction("Utility9", throwIfNotFound: true);
        m_PlayerControls_Utility10 = m_PlayerControls.FindAction("Utility10", throwIfNotFound: true);
        m_PlayerControls_Utility11 = m_PlayerControls.FindAction("Utility11", throwIfNotFound: true);
        m_PlayerControls_Utility12 = m_PlayerControls.FindAction("Utility12", throwIfNotFound: true);
        m_PlayerControls_Inventory = m_PlayerControls.FindAction("Inventory", throwIfNotFound: true);
        m_PlayerControls_CharacterSheet = m_PlayerControls.FindAction("CharacterSheet", throwIfNotFound: true);
        m_PlayerControls_Options = m_PlayerControls.FindAction("Options", throwIfNotFound: true);
        m_PlayerControls_Escape = m_PlayerControls.FindAction("Escape", throwIfNotFound: true);
        m_PlayerControls_Interaction = m_PlayerControls.FindAction("Interaction", throwIfNotFound: true);
        m_PlayerControls_Bionetic = m_PlayerControls.FindAction("Bionetic", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControls
    private readonly InputActionMap m_PlayerControls;
    private IPlayerControlsActions m_PlayerControlsActionsCallbackInterface;
    private readonly InputAction m_PlayerControls_Movement;
    private readonly InputAction m_PlayerControls_Cybernetic;
    private readonly InputAction m_PlayerControls_Look;
    private readonly InputAction m_PlayerControls_Weapon1;
    private readonly InputAction m_PlayerControls_Weapon2;
    private readonly InputAction m_PlayerControls_Weapon3;
    private readonly InputAction m_PlayerControls_Weapon3Up;
    private readonly InputAction m_PlayerControls_Weapon4;
    private readonly InputAction m_PlayerControls_Weapon4Up;
    private readonly InputAction m_PlayerControls_Utility5;
    private readonly InputAction m_PlayerControls_Utility6;
    private readonly InputAction m_PlayerControls_Utility7;
    private readonly InputAction m_PlayerControls_Utility8;
    private readonly InputAction m_PlayerControls_Utility9;
    private readonly InputAction m_PlayerControls_Utility10;
    private readonly InputAction m_PlayerControls_Utility11;
    private readonly InputAction m_PlayerControls_Utility12;
    private readonly InputAction m_PlayerControls_Inventory;
    private readonly InputAction m_PlayerControls_CharacterSheet;
    private readonly InputAction m_PlayerControls_Options;
    private readonly InputAction m_PlayerControls_Escape;
    private readonly InputAction m_PlayerControls_Interaction;
    private readonly InputAction m_PlayerControls_Bionetic;
    public struct PlayerControlsActions
    {
        private @MainControls m_Wrapper;
        public PlayerControlsActions(@MainControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerControls_Movement;
        public InputAction @Cybernetic => m_Wrapper.m_PlayerControls_Cybernetic;
        public InputAction @Look => m_Wrapper.m_PlayerControls_Look;
        public InputAction @Weapon1 => m_Wrapper.m_PlayerControls_Weapon1;
        public InputAction @Weapon2 => m_Wrapper.m_PlayerControls_Weapon2;
        public InputAction @Weapon3 => m_Wrapper.m_PlayerControls_Weapon3;
        public InputAction @Weapon3Up => m_Wrapper.m_PlayerControls_Weapon3Up;
        public InputAction @Weapon4 => m_Wrapper.m_PlayerControls_Weapon4;
        public InputAction @Weapon4Up => m_Wrapper.m_PlayerControls_Weapon4Up;
        public InputAction @Utility5 => m_Wrapper.m_PlayerControls_Utility5;
        public InputAction @Utility6 => m_Wrapper.m_PlayerControls_Utility6;
        public InputAction @Utility7 => m_Wrapper.m_PlayerControls_Utility7;
        public InputAction @Utility8 => m_Wrapper.m_PlayerControls_Utility8;
        public InputAction @Utility9 => m_Wrapper.m_PlayerControls_Utility9;
        public InputAction @Utility10 => m_Wrapper.m_PlayerControls_Utility10;
        public InputAction @Utility11 => m_Wrapper.m_PlayerControls_Utility11;
        public InputAction @Utility12 => m_Wrapper.m_PlayerControls_Utility12;
        public InputAction @Inventory => m_Wrapper.m_PlayerControls_Inventory;
        public InputAction @CharacterSheet => m_Wrapper.m_PlayerControls_CharacterSheet;
        public InputAction @Options => m_Wrapper.m_PlayerControls_Options;
        public InputAction @Escape => m_Wrapper.m_PlayerControls_Escape;
        public InputAction @Interaction => m_Wrapper.m_PlayerControls_Interaction;
        public InputAction @Bionetic => m_Wrapper.m_PlayerControls_Bionetic;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControlsActions instance)
        {
            if (m_Wrapper.m_PlayerControlsActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovement;
                @Cybernetic.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnCybernetic;
                @Cybernetic.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnCybernetic;
                @Cybernetic.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnCybernetic;
                @Look.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLook;
                @Weapon1.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon1;
                @Weapon1.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon1;
                @Weapon1.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon1;
                @Weapon2.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon2;
                @Weapon2.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon2;
                @Weapon2.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon2;
                @Weapon3.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon3;
                @Weapon3.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon3;
                @Weapon3.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon3;
                @Weapon3Up.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon3Up;
                @Weapon3Up.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon3Up;
                @Weapon3Up.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon3Up;
                @Weapon4.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon4;
                @Weapon4.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon4;
                @Weapon4.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon4;
                @Weapon4Up.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon4Up;
                @Weapon4Up.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon4Up;
                @Weapon4Up.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnWeapon4Up;
                @Utility5.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility5;
                @Utility5.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility5;
                @Utility5.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility5;
                @Utility6.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility6;
                @Utility6.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility6;
                @Utility6.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility6;
                @Utility7.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility7;
                @Utility7.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility7;
                @Utility7.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility7;
                @Utility8.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility8;
                @Utility8.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility8;
                @Utility8.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility8;
                @Utility9.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility9;
                @Utility9.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility9;
                @Utility9.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility9;
                @Utility10.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility10;
                @Utility10.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility10;
                @Utility10.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility10;
                @Utility11.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility11;
                @Utility11.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility11;
                @Utility11.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility11;
                @Utility12.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility12;
                @Utility12.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility12;
                @Utility12.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUtility12;
                @Inventory.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnInventory;
                @Inventory.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnInventory;
                @Inventory.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnInventory;
                @CharacterSheet.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnCharacterSheet;
                @CharacterSheet.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnCharacterSheet;
                @CharacterSheet.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnCharacterSheet;
                @Options.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnOptions;
                @Options.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnOptions;
                @Options.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnOptions;
                @Escape.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnEscape;
                @Interaction.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnInteraction;
                @Interaction.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnInteraction;
                @Interaction.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnInteraction;
                @Bionetic.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnBionetic;
                @Bionetic.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnBionetic;
                @Bionetic.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnBionetic;
            }
            m_Wrapper.m_PlayerControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Cybernetic.started += instance.OnCybernetic;
                @Cybernetic.performed += instance.OnCybernetic;
                @Cybernetic.canceled += instance.OnCybernetic;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Weapon1.started += instance.OnWeapon1;
                @Weapon1.performed += instance.OnWeapon1;
                @Weapon1.canceled += instance.OnWeapon1;
                @Weapon2.started += instance.OnWeapon2;
                @Weapon2.performed += instance.OnWeapon2;
                @Weapon2.canceled += instance.OnWeapon2;
                @Weapon3.started += instance.OnWeapon3;
                @Weapon3.performed += instance.OnWeapon3;
                @Weapon3.canceled += instance.OnWeapon3;
                @Weapon3Up.started += instance.OnWeapon3Up;
                @Weapon3Up.performed += instance.OnWeapon3Up;
                @Weapon3Up.canceled += instance.OnWeapon3Up;
                @Weapon4.started += instance.OnWeapon4;
                @Weapon4.performed += instance.OnWeapon4;
                @Weapon4.canceled += instance.OnWeapon4;
                @Weapon4Up.started += instance.OnWeapon4Up;
                @Weapon4Up.performed += instance.OnWeapon4Up;
                @Weapon4Up.canceled += instance.OnWeapon4Up;
                @Utility5.started += instance.OnUtility5;
                @Utility5.performed += instance.OnUtility5;
                @Utility5.canceled += instance.OnUtility5;
                @Utility6.started += instance.OnUtility6;
                @Utility6.performed += instance.OnUtility6;
                @Utility6.canceled += instance.OnUtility6;
                @Utility7.started += instance.OnUtility7;
                @Utility7.performed += instance.OnUtility7;
                @Utility7.canceled += instance.OnUtility7;
                @Utility8.started += instance.OnUtility8;
                @Utility8.performed += instance.OnUtility8;
                @Utility8.canceled += instance.OnUtility8;
                @Utility9.started += instance.OnUtility9;
                @Utility9.performed += instance.OnUtility9;
                @Utility9.canceled += instance.OnUtility9;
                @Utility10.started += instance.OnUtility10;
                @Utility10.performed += instance.OnUtility10;
                @Utility10.canceled += instance.OnUtility10;
                @Utility11.started += instance.OnUtility11;
                @Utility11.performed += instance.OnUtility11;
                @Utility11.canceled += instance.OnUtility11;
                @Utility12.started += instance.OnUtility12;
                @Utility12.performed += instance.OnUtility12;
                @Utility12.canceled += instance.OnUtility12;
                @Inventory.started += instance.OnInventory;
                @Inventory.performed += instance.OnInventory;
                @Inventory.canceled += instance.OnInventory;
                @CharacterSheet.started += instance.OnCharacterSheet;
                @CharacterSheet.performed += instance.OnCharacterSheet;
                @CharacterSheet.canceled += instance.OnCharacterSheet;
                @Options.started += instance.OnOptions;
                @Options.performed += instance.OnOptions;
                @Options.canceled += instance.OnOptions;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
                @Interaction.started += instance.OnInteraction;
                @Interaction.performed += instance.OnInteraction;
                @Interaction.canceled += instance.OnInteraction;
                @Bionetic.started += instance.OnBionetic;
                @Bionetic.performed += instance.OnBionetic;
                @Bionetic.canceled += instance.OnBionetic;
            }
        }
    }
    public PlayerControlsActions @PlayerControls => new PlayerControlsActions(this);
    public interface IPlayerControlsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCybernetic(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnWeapon1(InputAction.CallbackContext context);
        void OnWeapon2(InputAction.CallbackContext context);
        void OnWeapon3(InputAction.CallbackContext context);
        void OnWeapon3Up(InputAction.CallbackContext context);
        void OnWeapon4(InputAction.CallbackContext context);
        void OnWeapon4Up(InputAction.CallbackContext context);
        void OnUtility5(InputAction.CallbackContext context);
        void OnUtility6(InputAction.CallbackContext context);
        void OnUtility7(InputAction.CallbackContext context);
        void OnUtility8(InputAction.CallbackContext context);
        void OnUtility9(InputAction.CallbackContext context);
        void OnUtility10(InputAction.CallbackContext context);
        void OnUtility11(InputAction.CallbackContext context);
        void OnUtility12(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnCharacterSheet(InputAction.CallbackContext context);
        void OnOptions(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnBionetic(InputAction.CallbackContext context);
    }
}
